### ISSUE TITLE
twitter embeds broken in demo

### ISSUE THREAD

**Issue by hsavit1** [PaulieScanlon/gatsby-mdx-embed#15]

**Comment by spences10** [comment]
Hey @hsavit1, are you able to give a bit more information about what is broken?

I know it's a cliché but, it works on my machine.

If you are able to give specifics about the issue that may help @PaulieScanlon understand what might be causing the issue for you.

**Comment by PaulieScanlon** [comment]
@spences10 Thanks mate, appreciate you stepping in!

@hsavit1 As Scott mentioned it also works on my machine and on my blog where i use the plugin so i will need a little more info regarding your OS, browser and ideally a reproduction repo or code example to help you identify the problem.

Out of all of the embed scripts the Twitter one is the most reliable and i've not experienced any issues with it.

Happy to help if you can provide a little more info.
