### ISSUE TITLE
Improve Community Profile 

### ISSUE THREAD

**Issue by spences10** [PaulieScanlon/gatsby-mdx-embed#7]
Consider adding a 

- Licence
- Contributing Guide
- Issue/pull request template

![image](https://user-images.githubusercontent.com/234708/72979776-f9b37100-3dd0-11ea-9f20-90b8febdb5a7.png)

**Comment by PaulieScanlon** [comment]
@spences10 yeah I like this idea. I hadn’t thought about if anyone else might like to contribute! Good idea mate! I’ll look in to it!

**Comment by spences10** [comment]
I tried to fork the repo and use the templates on mine to push to yours but the community tab on forks isn't there 😢
